[2024-01-08T12:49:40.547+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.third_task manual__2024-01-08T12:49:35.948544+00:00 [queued]>
[2024-01-08T12:49:40.565+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.third_task manual__2024-01-08T12:49:35.948544+00:00 [queued]>
[2024-01-08T12:49:40.566+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-01-08T12:49:40.599+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): third_task> on 2024-01-08 12:49:35.948544+00:00
[2024-01-08T12:49:40.613+0000] {standard_task_runner.py:60} INFO - Started process 4153 to run task
[2024-01-08T12:49:40.618+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'third_task', 'manual__2024-01-08T12:49:35.948544+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpq59ltolu']
[2024-01-08T12:49:40.622+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask third_task
[2024-01-08T12:49:40.708+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v3.third_task manual__2024-01-08T12:49:35.948544+00:00 [running]> on host d3b0837e9e03
[2024-01-08T12:49:40.852+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arif' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T12:49:35.948544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-08T12:49:35.948544+00:00'
[2024-01-08T12:49:40.854+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T12:49:40.856+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 and with the same time as task2']
[2024-01-08T12:49:40.885+0000] {subprocess.py:86} INFO - Output:
[2024-01-08T12:49:40.887+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task1 and with the same time as task2
[2024-01-08T12:49:40.888+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-08T12:49:40.941+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, execution_date=20240108T124935, start_date=20240108T124940, end_date=20240108T124940
[2024-01-08T12:49:41.032+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-08T12:49:41.086+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
