[2024-01-08T13:06:57.624+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task manual__2024-01-08T13:06:53.130548+00:00 [queued]>
[2024-01-08T13:06:57.638+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task manual__2024-01-08T13:06:53.130548+00:00 [queued]>
[2024-01-08T13:06:57.638+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-01-08T13:06:57.659+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): third_task> on 2024-01-08 13:06:53.130548+00:00
[2024-01-08T13:06:57.666+0000] {standard_task_runner.py:60} INFO - Started process 4415 to run task
[2024-01-08T13:06:57.669+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'third_task', 'manual__2024-01-08T13:06:53.130548+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpka93nj87']
[2024-01-08T13:06:57.672+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask third_task
[2024-01-08T13:06:57.731+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v5.third_task manual__2024-01-08T13:06:53.130548+00:00 [running]> on host d3b0837e9e03
[2024-01-08T13:06:57.818+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arif' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T13:06:53.130548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-08T13:06:53.130548+00:00'
[2024-01-08T13:06:57.820+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T13:06:57.821+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 and with the same time as task2']
[2024-01-08T13:06:57.840+0000] {subprocess.py:86} INFO - Output:
[2024-01-08T13:06:57.842+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task1 and with the same time as task2
[2024-01-08T13:06:57.842+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-08T13:06:57.872+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=third_task, execution_date=20240108T130653, start_date=20240108T130657, end_date=20240108T130657
[2024-01-08T13:06:57.920+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-08T13:06:57.943+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
